### ISSUE TITLE
Not working with Jest 27.5.1

### ISSUE THREAD

**Issue by morewings** [dyakovk/jest-matchmedia-mock#19]
I have this test file:

```js
import { renderHook } from '@testing-library/react-hooks';
import matchMedia from '@/common/testUtils';
import { useMatchMedia } from './../useMatchMedia';

describe('useMatchMedia', () => {
    it('returns boolean', () => {
        const { result } = renderHook(() => useMatchMedia('(max-width: 575px)'));
        expect(result.current).toBe(expect.any(Boolean));
    });
});
```

with this hook

```js
import { useState, useEffect } from 'react';

export const useMatchMedia = (query: string) => {
    const [matches, setMatches] = useState(false);

    useEffect(() => {
        const media = window.matchMedia(query);
        if (media.matches !== matches) {
            setMatches(media.matches);
        }
        const listener = () => setMatches(media.matches);
        window.addEventListener('resize', listener);
        return () => window.removeEventListener('resize', listener);
    }, [matches, query]);

    return matches;
};
```

and have this error 

```
TypeError: window.matchMedia is not a function
```

Thanks.
